version: '3'
services:
  hass:
    container_name: hass
    image: homeassistant/home-assistant:stable
    privileged: true
    restart: always
    # volumes:
    #   - ./homeassistant:/config
    environment:
      - TZ=Europe/Paris
    # network_mode: host
    ports:
      - 8123:8123

  mqtt:
    container_name: mqtt
    image: eclipse-mosquitto
    restart: always
    ports:
      - 1883:1883
    volumes:
      - ./mqtt/mosquitto-no-auth.conf:/mosquitto/config/mosquitto.conf
      # - ./mqtt/mosquitto-auth.passwd:/mosquitto/config/mosquitto.passwd
  
  idiamant:
    container_name: idiamant
    # image: leclubber/idiamant2mqtt
    build: ./idiamant
    privileged: true
    restart: always
    environment:
      - MQTT_PORT=1883
      - MQTT_HOST=mqtt
      - MQTT_TOPIC=homeassistant
      - IDIAMANT_USER=${USER}
      - IDIAMANT_PASSWORD=${PASSWORD}
      - IDIAMANT_CLIENT_ID=${CLIENT_ID}
      - IDIAMANT_CLIENT_SECRET=${CLIENT_SECRET}
      - IDIAMANT_PULL_STATUS=5

